# Put your OpenRouter key here
OPENROUTER_API_KEY = "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"

# Optional: helps OpenRouter attribute traffic
APP_URL = "http://localhost:8501"
